name: Schedule run phpunit test suite

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  phpunit-test-suite:
    steps:
      - name: Testing
        uses: juzaweb/actions/.github/workflows/plugin-test.yml@main
        with:
          vendor: juzaweb
          plugin: ads-manager
